spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/history
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: always
  rabbitmq:
    host: localhost
    port: 4007
    username: guest
    password: guest